void Delta_spectrum_cell1()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:07 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.57075,7.625,2.279722);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell1__copy__1 = new TH1D("delta_histogram_for_chi2_cell1__copy__1","Data to MC difference in Cell 1",11,1.625,7.125);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(1,0.03460738);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(2,-0.5609175);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(3,-0.5484814);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(4,-0.3664183);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(5,-0.01956885);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(6,0.1242549);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(7,0.255044);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(8,0.5357787);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(9,-0.09091993);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(10,0.256036);
   delta_histogram_for_chi2_cell1__copy__1->SetBinContent(11,0.1322847);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell1__copy__1->SetMinimum(-1.843179);
   delta_histogram_for_chi2_cell1__copy__1->SetMaximum(1.843179);
   delta_histogram_for_chi2_cell1__copy__1->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#33cc33");
   delta_histogram_for_chi2_cell1__copy__1->SetLineColor(ci);
   delta_histogram_for_chi2_cell1__copy__1->SetLineWidth(3);

   ci = TColor::GetColor("#33cc33");
   delta_histogram_for_chi2_cell1__copy__1->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell1__copy__1->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell1__copy__1->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell1__copy__1->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell1__copy__1->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__1->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__1->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__1->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__1->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__1->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2 = new TH1D("E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(0,29.41722);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(1,0.6143932);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(2,0.5809181);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(3,0.4864486);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(4,0.4320364);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(5,0.3907283);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(6,0.3599564);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(7,0.3750472);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(8,0.3761497);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(9,0.3405572);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(10,0.2999338);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(11,0.2319574);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinContent(12,0.5812227);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinError(0,0.8431978);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetBinError(12,0.1765257);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__2->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell1__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#33cc33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#33cc33");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-1_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3 = new TH1D("E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3","E_reconstructed_Detector_IBD-Cell-1_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(0,-29.41722);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(1,-0.6143932);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(2,-0.5809181);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(3,-0.4864486);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(4,-0.4320364);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(5,-0.3907283);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(6,-0.3599564);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(7,-0.3750472);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(8,-0.3761497);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(9,-0.3405572);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(10,-0.2999338);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(11,-0.2319574);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinContent(12,-0.5812227);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinError(0,0.8431978);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetBinError(12,0.1765257);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI1_reference_energy_cell_spectra_envelope_histograms__copy__copy__3->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell1__copy__4 = new TH1D("delta_histogram_for_chi2_cell1__copy__4","Data to MC difference in Cell 1",11,1.625,7.125);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(1,0.03460738);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(2,-0.5609175);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(3,-0.5484814);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(4,-0.3664183);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(5,-0.01956885);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(6,0.1242549);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(7,0.255044);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(8,0.5357787);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(9,-0.09091993);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(10,0.256036);
   delta_histogram_for_chi2_cell1__copy__4->SetBinContent(11,0.1322847);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell1__copy__4->SetMinimum(-1.843179);
   delta_histogram_for_chi2_cell1__copy__4->SetMaximum(1.843179);
   delta_histogram_for_chi2_cell1__copy__4->SetEntries(13);

   ci = TColor::GetColor("#33cc33");
   delta_histogram_for_chi2_cell1__copy__4->SetLineColor(ci);
   delta_histogram_for_chi2_cell1__copy__4->SetLineWidth(3);

   ci = TColor::GetColor("#33cc33");
   delta_histogram_for_chi2_cell1__copy__4->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell1__copy__4->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell1__copy__4->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell1__copy__4->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell1__copy__4->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__4->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell1__copy__4->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell1__copy__4->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell1__copy__4->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell1__copy__4->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6540602,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 1");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
