void Delta_spectrum_cell6()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:25 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.450557,7.625,2.173135);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell6__copy__21 = new TH1D("delta_histogram_for_chi2_cell6__copy__21","Data to MC difference in Cell 6",11,1.625,7.125);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(1,0.5520848);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(2,-0.06543878);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(3,0.6955234);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(4,0.03259986);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(5,0.2983788);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(6,-0.4972687);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(7,-0.03501839);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(8,-0.6300412);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(9,-0.02519793);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(10,0.3927554);
   delta_histogram_for_chi2_cell6__copy__21->SetBinContent(11,-0.2427865);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell6__copy__21->SetMinimum(-1.757003);
   delta_histogram_for_chi2_cell6__copy__21->SetMaximum(1.757003);
   delta_histogram_for_chi2_cell6__copy__21->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   delta_histogram_for_chi2_cell6__copy__21->SetLineColor(ci);
   delta_histogram_for_chi2_cell6__copy__21->SetLineWidth(3);

   ci = TColor::GetColor("#000099");
   delta_histogram_for_chi2_cell6__copy__21->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell6__copy__21->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell6__copy__21->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell6__copy__21->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell6__copy__21->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__21->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__21->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__21->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__21->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__21->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22 = new TH1D("E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(0,13.26813);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(1,0.5856676);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(2,0.5504203);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(3,0.4663309);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(4,0.3993782);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(5,0.3560735);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(6,0.3538755);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(7,0.3714928);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(8,0.3798279);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(9,0.3257822);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(10,0.2673573);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(11,0.2221413);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinContent(12,0.2524986);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinError(0,0.8183489);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetBinError(12,0.1477673);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__22->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell6__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#000099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-6_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23 = new TH1D("E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23","E_reconstructed_Detector_IBD-Cell-6_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(0,-13.26813);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(1,-0.5856676);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(2,-0.5504203);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(3,-0.4663309);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(4,-0.3993782);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(5,-0.3560735);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(6,-0.3538755);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(7,-0.3714928);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(8,-0.3798279);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(9,-0.3257822);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(10,-0.2673573);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(11,-0.2221413);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinContent(12,-0.2524986);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinError(0,0.8183489);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetBinError(12,0.1477673);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI6_reference_energy_cell_spectra_envelope_histograms__copy__copy__23->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell6__copy__24 = new TH1D("delta_histogram_for_chi2_cell6__copy__24","Data to MC difference in Cell 6",11,1.625,7.125);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(1,0.5520848);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(2,-0.06543878);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(3,0.6955234);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(4,0.03259986);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(5,0.2983788);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(6,-0.4972687);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(7,-0.03501839);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(8,-0.6300412);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(9,-0.02519793);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(10,0.3927554);
   delta_histogram_for_chi2_cell6__copy__24->SetBinContent(11,-0.2427865);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell6__copy__24->SetMinimum(-1.757003);
   delta_histogram_for_chi2_cell6__copy__24->SetMaximum(1.757003);
   delta_histogram_for_chi2_cell6__copy__24->SetEntries(13);

   ci = TColor::GetColor("#000099");
   delta_histogram_for_chi2_cell6__copy__24->SetLineColor(ci);
   delta_histogram_for_chi2_cell6__copy__24->SetLineWidth(3);

   ci = TColor::GetColor("#000099");
   delta_histogram_for_chi2_cell6__copy__24->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell6__copy__24->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell6__copy__24->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell6__copy__24->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell6__copy__24->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__24->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell6__copy__24->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell6__copy__24->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell6__copy__24->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell6__copy__24->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6603258,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 6");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
