void Delta_spectrum_cell2()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:11 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.754841,7.625,2.442972);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell2__copy__5 = new TH1D("delta_histogram_for_chi2_cell2__copy__5","Data to MC difference in Cell 2",11,1.625,7.125);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(1,0.1932516);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(2,0.5266824);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(3,0.190029);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(4,0.3518654);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(5,0.2293788);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(6,-0.1095348);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(7,0.0863754);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(8,0.5039436);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(9,-0.6331858);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(10,-0.2839891);
   delta_histogram_for_chi2_cell2__copy__5->SetBinContent(11,-0.03139733);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell2__copy__5->SetMinimum(-1.975169);
   delta_histogram_for_chi2_cell2__copy__5->SetMaximum(1.975169);
   delta_histogram_for_chi2_cell2__copy__5->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#006633");
   delta_histogram_for_chi2_cell2__copy__5->SetLineColor(ci);
   delta_histogram_for_chi2_cell2__copy__5->SetLineWidth(3);

   ci = TColor::GetColor("#006633");
   delta_histogram_for_chi2_cell2__copy__5->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell2__copy__5->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell2__copy__5->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell2__copy__5->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell2__copy__5->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__5->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__5->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__5->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__5->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__5->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6 = new TH1D("E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(0,27.77328);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(1,0.6583897);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(2,0.6152795);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(3,0.5271802);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(4,0.4426286);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(5,0.3992185);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(6,0.3760519);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(7,0.3902525);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(8,0.4188557);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(9,0.3677449);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(10,0.3030978);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(11,0.2363699);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinContent(12,0.6470835);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinError(0,0.795658);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetBinError(12,0.1782258);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__6->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell2__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006633");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#006633");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-2_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7 = new TH1D("E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7","E_reconstructed_Detector_IBD-Cell-2_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(0,-27.77328);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(1,-0.6583897);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(2,-0.6152795);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(3,-0.5271802);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(4,-0.4426286);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(5,-0.3992185);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(6,-0.3760519);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(7,-0.3902525);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(8,-0.4188557);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(9,-0.3677449);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(10,-0.3030978);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(11,-0.2363699);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinContent(12,-0.6470835);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinError(0,0.795658);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetBinError(12,0.1782258);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI2_reference_energy_cell_spectra_envelope_histograms__copy__copy__7->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell2__copy__8 = new TH1D("delta_histogram_for_chi2_cell2__copy__8","Data to MC difference in Cell 2",11,1.625,7.125);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(1,0.1932516);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(2,0.5266824);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(3,0.190029);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(4,0.3518654);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(5,0.2293788);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(6,-0.1095348);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(7,0.0863754);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(8,0.5039436);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(9,-0.6331858);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(10,-0.2839891);
   delta_histogram_for_chi2_cell2__copy__8->SetBinContent(11,-0.03139733);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell2__copy__8->SetMinimum(-1.975169);
   delta_histogram_for_chi2_cell2__copy__8->SetMaximum(1.975169);
   delta_histogram_for_chi2_cell2__copy__8->SetEntries(13);

   ci = TColor::GetColor("#006633");
   delta_histogram_for_chi2_cell2__copy__8->SetLineColor(ci);
   delta_histogram_for_chi2_cell2__copy__8->SetLineWidth(3);

   ci = TColor::GetColor("#006633");
   delta_histogram_for_chi2_cell2__copy__8->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell2__copy__8->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell2__copy__8->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell2__copy__8->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell2__copy__8->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__8->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell2__copy__8->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell2__copy__8->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell2__copy__8->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell2__copy__8->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6603258,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 2");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
