void Delta_spectrum_cell4()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:18 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.72306,7.625,2.414789);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell4__copy__13 = new TH1D("delta_histogram_for_chi2_cell4__copy__13","Data to MC difference in Cell 4",11,1.625,7.125);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(1,0.1310501);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(2,-0.06820893);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(3,-0.3788241);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(4,-0.007518283);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(5,-0.353312);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(6,0.4288718);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(7,0.228111);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(8,0.2946214);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(9,0.2648115);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(10,-0.2884888);
   delta_histogram_for_chi2_cell4__copy__13->SetBinContent(11,0.1658991);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell4__copy__13->SetMinimum(-1.952382);
   delta_histogram_for_chi2_cell4__copy__13->SetMaximum(1.952382);
   delta_histogram_for_chi2_cell4__copy__13->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#339999");
   delta_histogram_for_chi2_cell4__copy__13->SetLineColor(ci);
   delta_histogram_for_chi2_cell4__copy__13->SetLineWidth(3);

   ci = TColor::GetColor("#339999");
   delta_histogram_for_chi2_cell4__copy__13->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell4__copy__13->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell4__copy__13->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell4__copy__13->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell4__copy__13->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__13->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__13->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__13->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__13->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__13->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14 = new TH1D("E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(0,21.26088);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(1,0.6507942);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(2,0.6111956);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(3,0.5389358);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(4,0.4411524);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(5,0.3984639);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(6,0.369039);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(7,0.4075005);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(8,0.4284317);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(9,0.3567955);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(10,0.3108049);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(11,0.2424085);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinContent(12,0.5368706);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinError(0,0.8136819);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetBinError(12,0.1779773);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__14->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell4__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#339999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#339999");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-4_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15 = new TH1D("E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15","E_reconstructed_Detector_IBD-Cell-4_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(0,-21.26088);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(1,-0.6507942);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(2,-0.6111956);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(3,-0.5389358);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(4,-0.4411524);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(5,-0.3984639);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(6,-0.369039);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(7,-0.4075005);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(8,-0.4284317);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(9,-0.3567955);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(10,-0.3108049);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(11,-0.2424085);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinContent(12,-0.5368706);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinError(0,0.8136819);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetBinError(12,0.1779773);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI4_reference_energy_cell_spectra_envelope_histograms__copy__copy__15->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell4__copy__16 = new TH1D("delta_histogram_for_chi2_cell4__copy__16","Data to MC difference in Cell 4",11,1.625,7.125);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(1,0.1310501);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(2,-0.06820893);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(3,-0.3788241);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(4,-0.007518283);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(5,-0.353312);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(6,0.4288718);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(7,0.228111);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(8,0.2946214);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(9,0.2648115);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(10,-0.2884888);
   delta_histogram_for_chi2_cell4__copy__16->SetBinContent(11,0.1658991);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell4__copy__16->SetMinimum(-1.952382);
   delta_histogram_for_chi2_cell4__copy__16->SetMaximum(1.952382);
   delta_histogram_for_chi2_cell4__copy__16->SetEntries(13);

   ci = TColor::GetColor("#339999");
   delta_histogram_for_chi2_cell4__copy__16->SetLineColor(ci);
   delta_histogram_for_chi2_cell4__copy__16->SetLineWidth(3);

   ci = TColor::GetColor("#339999");
   delta_histogram_for_chi2_cell4__copy__16->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell4__copy__16->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell4__copy__16->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell4__copy__16->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell4__copy__16->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__16->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell4__copy__16->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell4__copy__16->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell4__copy__16->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell4__copy__16->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6603258,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 4");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
