void Delta_spectrum_cell3()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:14 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.680301,7.625,2.37687);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell3__copy__9 = new TH1D("delta_histogram_for_chi2_cell3__copy__9","Data to MC difference in Cell 3",11,1.625,7.125);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(1,-0.7418619);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(2,0.07056156);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(3,-0.2053861);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(4,0.05761186);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(5,0.38355);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(6,-0.1291307);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(7,-0.3333167);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(8,-0.6909381);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(9,0.06308063);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(10,-0.1267011);
   delta_histogram_for_chi2_cell3__copy__9->SetBinContent(11,0.1245192);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell3__copy__9->SetMinimum(-1.921725);
   delta_histogram_for_chi2_cell3__copy__9->SetMaximum(1.921725);
   delta_histogram_for_chi2_cell3__copy__9->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0099ff");
   delta_histogram_for_chi2_cell3__copy__9->SetLineColor(ci);
   delta_histogram_for_chi2_cell3__copy__9->SetLineWidth(3);

   ci = TColor::GetColor("#0099ff");
   delta_histogram_for_chi2_cell3__copy__9->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell3__copy__9->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell3__copy__9->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell3__copy__9->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell3__copy__9->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__9->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__9->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__9->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__9->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__9->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10 = new TH1D("E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(0,25.16261);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(1,0.640575);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(2,0.6091253);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(3,0.5215591);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(4,0.4434111);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(5,0.3901937);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(6,0.3617059);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(7,0.3910751);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(8,0.4188079);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(9,0.3679036);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(10,0.2938057);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(11,0.2456299);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinContent(12,0.6427084);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinError(0,0.8254069);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetBinError(12,0.1940959);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__10->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell3__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0099ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#0099ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-3_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11 = new TH1D("E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11","E_reconstructed_Detector_IBD-Cell-3_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(0,-25.16261);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(1,-0.640575);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(2,-0.6091253);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(3,-0.5215591);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(4,-0.4434111);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(5,-0.3901937);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(6,-0.3617059);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(7,-0.3910751);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(8,-0.4188079);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(9,-0.3679036);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(10,-0.2938057);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(11,-0.2456299);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinContent(12,-0.6427084);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinError(0,0.8254069);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetBinError(12,0.1940959);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI3_reference_energy_cell_spectra_envelope_histograms__copy__copy__11->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell3__copy__12 = new TH1D("delta_histogram_for_chi2_cell3__copy__12","Data to MC difference in Cell 3",11,1.625,7.125);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(1,-0.7418619);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(2,0.07056156);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(3,-0.2053861);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(4,0.05761186);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(5,0.38355);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(6,-0.1291307);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(7,-0.3333167);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(8,-0.6909381);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(9,0.06308063);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(10,-0.1267011);
   delta_histogram_for_chi2_cell3__copy__12->SetBinContent(11,0.1245192);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell3__copy__12->SetMinimum(-1.921725);
   delta_histogram_for_chi2_cell3__copy__12->SetMaximum(1.921725);
   delta_histogram_for_chi2_cell3__copy__12->SetEntries(13);

   ci = TColor::GetColor("#0099ff");
   delta_histogram_for_chi2_cell3__copy__12->SetLineColor(ci);
   delta_histogram_for_chi2_cell3__copy__12->SetLineWidth(3);

   ci = TColor::GetColor("#0099ff");
   delta_histogram_for_chi2_cell3__copy__12->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell3__copy__12->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell3__copy__12->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell3__copy__12->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell3__copy__12->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__12->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell3__copy__12->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell3__copy__12->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell3__copy__12->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell3__copy__12->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6603258,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 3");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
