void Delta_spectrum_cell5()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Jul 13 15:54:21 2019) by ROOT version 6.13/02
   TCanvas *c1 = new TCanvas("c1", "c1",0,23,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4821429,-2.637221,7.625,2.338668);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *delta_histogram_for_chi2_cell5__copy__17 = new TH1D("delta_histogram_for_chi2_cell5__copy__17","Data to MC difference in Cell 5",11,1.625,7.125);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(1,-0.2788924);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(2,0.1496993);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(3,0.1148923);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(4,-0.05395023);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(5,-0.6734009);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(6,0.2306943);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(7,-0.2198107);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(8,-0.01431412);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(9,0.4673134);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(10,-0.07067053);
   delta_histogram_for_chi2_cell5__copy__17->SetBinContent(11,-0.1086242);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell5__copy__17->SetMinimum(-1.890838);
   delta_histogram_for_chi2_cell5__copy__17->SetMaximum(1.890838);
   delta_histogram_for_chi2_cell5__copy__17->SetEntries(13);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#6666ff");
   delta_histogram_for_chi2_cell5__copy__17->SetLineColor(ci);
   delta_histogram_for_chi2_cell5__copy__17->SetLineWidth(3);

   ci = TColor::GetColor("#6666ff");
   delta_histogram_for_chi2_cell5__copy__17->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell5__copy__17->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell5__copy__17->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell5__copy__17->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell5__copy__17->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__17->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__17->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__17->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__17->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__17->Draw("");
   
   TH1D *E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18 = new TH1D("E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18","1#sigma stat + syst errors",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(0,18.63039);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(1,0.6302792);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(2,0.6112442);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(3,0.5172591);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(4,0.4422994);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(5,0.4136031);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(6,0.3628438);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(7,0.4011358);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(8,0.4430677);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(9,0.3716369);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(10,0.2926147);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(11,0.2475168);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinContent(12,0.4344857);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinError(0,0.8528394);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetBinError(12,0.1770263);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetLineColor(ci);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetLineWidth(0);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__18->Draw("BARSAME");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("delta_histogram_for_chi2_cell5__copy","#Delta_{cb} = (D_{cb} - #phi_{b}M_{cb})    ","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#6666ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);

   ci = TColor::GetColor("#6666ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("E_reconstructed_Detector_IBD-Cell-5_reference_energy_cell_spectra_envelope_histograms__copy","1#sigma stat + syst errors","lpflpf");

   ci = TColor::GetColor("#999999");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3002);

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19 = new TH1D("E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19","E_reconstructed_Detector_IBD-Cell-5_reference_energy_cell_spectra_envelope_histograms__copy__copy",11,1.625,7.125);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(0,-18.63039);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(1,-0.6302792);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(2,-0.6112442);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(3,-0.5172591);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(4,-0.4422994);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(5,-0.4136031);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(6,-0.3628438);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(7,-0.4011358);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(8,-0.4430677);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(9,-0.3716369);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(10,-0.2926147);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(11,-0.2475168);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinContent(12,-0.4344857);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinError(0,0.8528394);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetBinError(12,0.1770263);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetEntries(26);

   ci = TColor::GetColor("#999999");
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetFillColor(ci);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetFillStyle(3002);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetLineWidth(3);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->SetMarkerSize(1.2);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetTitleOffset(1.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetXaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetLabelOffset(0.015);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetTitleOffset(1.2);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetYaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetZaxis()->SetLabelFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetZaxis()->SetLabelSize(0.05);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetZaxis()->SetTitleSize(0.06);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->GetZaxis()->SetTitleFont(42);
   E_reconstructed_Detector_IBDmICellmI5_reference_energy_cell_spectra_envelope_histograms__copy__copy__19->Draw("BARSAME");
   
   TH1D *delta_histogram_for_chi2_cell5__copy__20 = new TH1D("delta_histogram_for_chi2_cell5__copy__20","Data to MC difference in Cell 5",11,1.625,7.125);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(1,-0.2788924);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(2,0.1496993);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(3,0.1148923);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(4,-0.05395023);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(5,-0.6734009);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(6,0.2306943);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(7,-0.2198107);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(8,-0.01431412);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(9,0.4673134);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(10,-0.07067053);
   delta_histogram_for_chi2_cell5__copy__20->SetBinContent(11,-0.1086242);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(0,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(1,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(2,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(3,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(4,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(5,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(6,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(7,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(8,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(9,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(10,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(11,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetBinError(12,0.001);
   delta_histogram_for_chi2_cell5__copy__20->SetMinimum(-1.890838);
   delta_histogram_for_chi2_cell5__copy__20->SetMaximum(1.890838);
   delta_histogram_for_chi2_cell5__copy__20->SetEntries(13);

   ci = TColor::GetColor("#6666ff");
   delta_histogram_for_chi2_cell5__copy__20->SetLineColor(ci);
   delta_histogram_for_chi2_cell5__copy__20->SetLineWidth(3);

   ci = TColor::GetColor("#6666ff");
   delta_histogram_for_chi2_cell5__copy__20->SetMarkerColor(ci);
   delta_histogram_for_chi2_cell5__copy__20->SetMarkerStyle(8);
   delta_histogram_for_chi2_cell5__copy__20->SetMarkerSize(1.2);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetTitle("Reconstructed Energy (MeV)");
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetTitleOffset(1.05);
   delta_histogram_for_chi2_cell5__copy__20->GetXaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetTitle("#Delta_{cb} (/day/500keV)");
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetLabelOffset(0.015);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetTitleOffset(1.2);
   delta_histogram_for_chi2_cell5__copy__20->GetYaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__20->GetZaxis()->SetLabelFont(42);
   delta_histogram_for_chi2_cell5__copy__20->GetZaxis()->SetLabelSize(0.05);
   delta_histogram_for_chi2_cell5__copy__20->GetZaxis()->SetTitleSize(0.06);
   delta_histogram_for_chi2_cell5__copy__20->GetZaxis()->SetTitleFont(42);
   delta_histogram_for_chi2_cell5__copy__20->Draw("SAME");
   
   TPaveText *pt = new TPaveText(0.01,0.929,0.6603258,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   TText *pt_LaTex = pt->AddText("Data to MC difference in Cell 5");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
